# fly.toml app configuration file generated for birb-service on 2023-12-09T22:43:38+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "birb-service"
primary_region = "hkg"

[build]

[[services]]
  internal_port = 9000
  protocol = "tcp"
  processes = ["app"]
  http_checks = []
  script_checks = []

  [[services.ports]]
    handlers = ["tls"]
    port = 443

  [services.ports.tls_options]
    alpn = ["h2"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
